-- CreateTable
CREATE TABLE `bike_specs` (
    `id` VARCHAR(191) NOT NULL,
    `model_id` VARCHAR(160) NOT NULL,
    `brand_slug` VARCHAR(80) NOT NULL,
    `model_slug` VARCHAR(120) NOT NULL,
    `model_name` VARCHAR(200) NOT NULL,
    `source_url` VARCHAR(500) NOT NULL,
    `source` VARCHAR(40) NOT NULL DEFAULT 'bikedekho',

    `displacement_cc` INTEGER NULL,
    `engine_type` VARCHAR(200) NULL,
    `cylinders` INTEGER NULL,
    `max_power_ps` DECIMAL(7, 2) NULL,
    `max_power_rpm` INTEGER NULL,
    `max_torque_nm` DECIMAL(7, 2) NULL,
    `max_torque_rpm` INTEGER NULL,
    `top_speed_kmph` INTEGER NULL,
    `cooling_system` VARCHAR(80) NULL,
    `starting_system` VARCHAR(80) NULL,
    `transmission_type` VARCHAR(60) NULL,
    `gears` INTEGER NULL,
    `drive_type` VARCHAR(60) NULL,
    `emission_norm` VARCHAR(40) NULL,

    `mileage_city_kmpl` DECIMAL(6, 2) NULL,
    `mileage_highway_kmpl` DECIMAL(6, 2) NULL,
    `mileage_overall_kmpl` DECIMAL(6, 2) NULL,

    `seat_height_mm` INTEGER NULL,
    `kerb_weight_kg` DECIMAL(6, 2) NULL,
    `ground_clearance_mm` INTEGER NULL,
    `wheelbase_mm` INTEGER NULL,
    `length_mm` INTEGER NULL,
    `width_mm` INTEGER NULL,
    `height_mm` INTEGER NULL,
    `fuel_tank_l` DECIMAL(5, 2) NULL,
    `fuel_reserve_l` DECIMAL(5, 2) NULL,

    `front_brake` VARCHAR(60) NULL,
    `rear_brake` VARCHAR(60) NULL,
    `abs_type` VARCHAR(60) NULL,
    `tyre_front` VARCHAR(80) NULL,
    `tyre_rear` VARCHAR(80) NULL,
    `wheel_type` VARCHAR(60) NULL,
    `front_suspension` VARCHAR(300) NULL,
    `rear_suspension` VARCHAR(300) NULL,

    `warranty_years` INTEGER NULL,
    `warranty_km` INTEGER NULL,
    `first_service_km` INTEGER NULL,
    `service_interval_km` INTEGER NULL,

    `battery_kwh` DECIMAL(6, 2) NULL,
    `claimed_range_km` INTEGER NULL,
    `charge_time_hrs` DECIMAL(5, 2) NULL,
    `motor_kw` DECIMAL(6, 2) NULL,

    `body_type_raw` VARCHAR(80) NULL,
    `body_type` VARCHAR(40) NULL,
    `riding_posture` VARCHAR(40) NULL,
    `power_to_weight` DECIMAL(7, 3) NULL,
    `is_electric` BOOLEAN NOT NULL DEFAULT false,
    `is_upcoming` BOOLEAN NOT NULL DEFAULT false,

    `rating_avg` DECIMAL(3, 2) NULL,
    `rating_count` INTEGER NULL,

    `raw_specs` TEXT NULL,
    `completeness` INTEGER NOT NULL DEFAULT 0,

    `last_scraped_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `bike_specs_model_id_key`(`model_id`),
    INDEX `bike_specs_brand_slug_idx`(`brand_slug`),
    INDEX `bike_specs_displacement_cc_idx`(`displacement_cc`),
    INDEX `bike_specs_seat_height_mm_idx`(`seat_height_mm`),
    INDEX `bike_specs_body_type_idx`(`body_type`),
    INDEX `bike_specs_completeness_idx`(`completeness`),
    INDEX `bike_specs_is_upcoming_idx`(`is_upcoming`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
